project:
  type: website
  output-dir: docs

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: construction.qmd
        text: Construction
      - href: operation-maintenance.qmd
        text: Operation & Maintenance
    right:
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch?subject=Low-Cost Incinerator Design"
        aria-label: Email
      - icon: github
        href: https://github.com/Global-Health-Engineering/incinerator-design-cape-maclear
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#ghe-open:staffchat.ethz.ch
        aria-label: Matrix
  page-footer:
      left: |
          This project was supported by the
          [Global Health Engineering Group at ETH Zurich](https://ghe.ethz.ch)
      right:
        - icon: "envelope-at"
          href: "mailto:ghe@mavt.ethz.ch?subject=Low-Cost Incinerator Design"
          aria-label: Email
        - icon: github
          href: https://github.com/Global-Health-Engineering/incinerator-design-cape-maclear
          aria-label: GitHub
        - icon: chat-left-dots
          href: https://matrix.to/#/#ghe-open:staffchat.ethz.ch
          aria-label: Matrix

format:
  html:
    theme:
      light: [litera, theme.scss]
    highlight-style: a11y-dark
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <script defer data-domain="global-health-engineering.github.io/glass-crusher-design" src="https://plausible.io/js/script.js"></script>
